apiVersion: v1
kind: Service
metadata:
  name: saludo-service
  namespace: saludo
  labels:
    app: saludo-service
spec:
  selector:
    app: saludo-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
